### ISSUE TITLE
Homebrew support

### ISSUE THREAD

**Issue by BalestraPatrick** [JohnSundell/SwiftPlate#1]
Hey! Not sure how and if it could work, but would it be possible to install `SwiftPlate` via Homebrew? 👍

**Comment by BalestraPatrick** [comment]
Update: Just realized I can run it with `swift main.swift` but it's not mentioned in the README. Is this a supported way to run the project? :)

**Comment by JohnSundell** [comment]
@BalestraPatrick Sure, you can compile & run `main.swift` directly, no problems! 👍 For Homebrew, someone (hint hint 😉) other than me needs to submit the formula (they state `We frown on authors submitting their own work unless it is very popular.` in their docs). 😇

**Comment by codeOfRobin** [comment]
@JohnSundell You'll have to tag a release. After that, I can submit to homebrew 🤓

**Comment by JohnSundell** [comment]
@codeOfRobin Done! 🚀 https://github.com/JohnSundell/SwiftPlate/releases/tag/1.0.0. Thanks for helping out 💃

**Comment by codeOfRobin** [comment]
Awesome! I'll have it done by tomorrow.

**Comment by JohnSundell** [comment]
@codeOfRobin That is amazing! Thank you so much! 👍

**Comment by codeOfRobin** [comment]
@JohnSundell I'll have to add a Makefile. Making a PR in a moment.

**Comment by codeOfRobin** [comment]
Okay, so updates.

1. The install script is up and running, no issues there.
2. the test part needs some work. It needs to create a directory(ideally), run `swiftplate`, somehow supply all the arguments needed, then run `testStructure.py`. I have a few ideas on how we could do this:-

- We could supply arguments to swiftplate via a .json file(would require changes in the source)
- We could somehow pass in the arguments via `STDIN`. (I'm not nearly enough of a unix nerd to do this)
- (slightly half-assed solution) We could create a test repo (updated by clearing a directory and running the latest version of `swiftplate`, download contents of that test repo and test against it (and make sure that test repo is always updated with the changes in `swiftplate`). This solution makes me 😒, but it's the fastest.

@JohnSundell How hard would it be to accept a JSON file, parse it and use that to generate a project (I imagine not much, since JSONSerialization is available on both MacOS and Linux)

**Comment by JohnSundell** [comment]
I think adding the option of supplying SwiftPlate's options via `STDIN` probably makes the most sense. It would also make it easier to use it from for example CI, to be able to automate the automatic generation of projects 😅! I can work on this during the weekend if no one else picks it up.

**Comment by codeOfRobin** [comment]
@JohnSundell You mean like `--argument-name value`? That did not cross my mind. I volunteer ✋.

**Comment by JohnSundell** [comment]
@codeOfRobin Yeah exactly! That's awesome - all yours! 🚀

**Comment by JohnSundell** [comment]
We now have Homebrew support, thanks to @codeOfRobin! 🎉 Just `$ brew install swiftplate` 🚀
